# Generated by Django 3.2.8 on 2021-11-18 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Btype', models.IntegerField(blank=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('Counter1', models.IntegerField(blank=True)),
                ('Counter2', models.IntegerField(blank=True)),
                ('Counter3', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(default='Visitor', max_length=50)),
                ('AccesList', models.CharField(blank=True, max_length=1000)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.CharField(max_length=5)),
                ('Description', models.TextField(blank=True)),
                ('FixTime', models.DateTimeField(auto_now=True)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField(blank=True)),
                ('Type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.accidentstype')),
            ],
        ),
    ]
