# Generated by Django 3.2.8 on 2021-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidents',
            name='StartTime',
        ),
        migrations.AlterField(
            model_name='buttons',
            name='TimeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
