# Generated by Django 3.2.8 on 2021-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211120_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentstype',
            name='TypeName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
