# Generated by Django 3.2.8 on 2021-11-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_accidentstype_typename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidents',
            name='FixTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accidents',
            name='Post',
            field=models.CharField(max_length=20),
        ),
    ]
