# Generated by Django 3.2.8 on 2021-11-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211120_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidents',
            name='EndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidents',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.accidentstype'),
        ),
    ]
