# Generated by Django 3.2.8 on 2021-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211120_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidents',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buttons',
            name='Btype',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='buttons',
            name='TimeStamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
